#!/bin/bash

sysctl net.ipv4.conf.all.forwarding=1
#   internet 
ip a add dev internet 10.87.0.254/24
iptables -t nat -A POSTROUTING -s 10.87.0.0/24 -j MASQUERADE
#   RA
ip netns exec RA ip route add default via 10.87.0.254
ip netns exec RA iptables -t nat -A POSTROUTING -s 172.16.1.0/24 -j MASQUERADE
#   RB
ip netns exec RB ip route add default via 10.87.0.254
ip netns exec RB iptables -t nat -A POSTROUTING -s 172.16.2.0/24 -j MASQUERADE
#   R1
ip netns exec R1 iptables -t nat -A POSTROUTING -s 192.168.100.0/24 -j MASQUERADE
ip netns exec R1 iptables -t nat -A POSTROUTING -s 192.168.200.0/24 -j MASQUERADE
#   R2
ip netns exec R2 iptables -t nat -A POSTROUTING -s 192.168.100.0/24 -j MASQUERADE
ip netns exec R2 iptables -t nat -A POSTROUTING -s 192.168.200.0/24 -j MASQUERADE
